name: Release and publish to npm
on:
  workflow_dispatch:
    inputs:
      input_version:
        type: choice
        description: What type of release?
        options:
          - patch
          - minor
          - major

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Debug inputs
        run: |
          echo "Type of release:${{ github.event.inputs.input_version }} from user ${GITHUB_ACTOR}"
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: lts/*
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            node_modules
          key: node-modules
      - name: Install dependencies
        run: npm i
      - name: Authenticate with registry
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Run release-it
        run: npx release-it ${{ github.event.inputs.input_version }} --ci
      - name: Create commit message
        run: |
          echo "chore: release $(jq -r '.version' package.json)" > commitMessageFile
      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@2a9d9e983e611793b54516a18e48361bbac691d9 # v1.4.1
        with:
          message-file: commitMessageFile
          files: |
            CHANGELOG.md
            package.json
            package-lock.json
      - name: Attest
        uses: actions/attest-build-provenance@520d128f165991a6c774bcb264f323e3d70747f4 # v2.2.0
        with:
          subject-path: '${{ github.workspace }}/*.tgz'
